### ISSUE TITLE
Added level 4 and 5

### ISSUE THREAD

**Issue by vzorglub** [rogeriopvl/windrose#5]
Hello,
I have extended the file to add level 4 and 5 for the navigators among us
I am also working of translation
Thanks
[Windrose.txt](https://github.com/rogeriopvl/windrose/files/1571257/Windrose.txt)

**Comment by rogeriopvl** [comment]
Thanks @vzorglub 

Can you make a pull request with the changes? Let me know if you need help with this 👍

**Comment by vzorglub** [comment]
Yes, please
I don't even know what it means

**Comment by vzorglub** [comment]
Yes, could you help with the pull request, please
Thank you
